(define (problem goal4_step1)
  (:domain blocks-goal4)
  (:objects
    y1 y2 y3 y4 y5 y6 y7 y8 y9 y10 y11 y12 g1 g2 g3 g4 g5 g6 - block
    pos_r1_c2_bottom pos_r1_c3_bottom pos_r1_c2_top pos_r1_c3_top pos_r2_c1_bottom pos_r2_c4_bottom pos_r2_c1_top pos_r2_c4_top pos_r3_c2_bottom pos_r3_c3_bottom pos_r3_c2_top pos_r3_c3_top pos_front_center_bottom pos_front_right_bottom pos_middle_left_bottom pos_middle_right_bottom pos_back_left_bottom pos_back_center_bottom pos_middle_center_bottom - position
  )
  (:init
    (at-position y10 pos_r3_c3_top)
    (at-position y2 pos_r1_c3_bottom)
    (at-position y5 pos_r2_c1_bottom)
    (at-position y9 pos_r3_c2_bottom)
    (clear g1)
    (clear g2)
    (clear g3)
    (clear g4)
    (clear g5)
    (clear g6)
    (clear y1)
    (clear y10)
    (clear y11)
    (clear y12)
    (clear y2)
    (clear y3)
    (clear y4)
    (clear y5)
    (clear y6)
    (clear y7)
    (clear y8)
    (clear y9)
    (handempty)
    (ontable g1)
    (ontable g2)
    (ontable g3)
    (ontable g4)
    (ontable g5)
    (ontable g6)
    (ontable y1)
    (ontable y11)
    (ontable y12)
    (ontable y2)
    (ontable y3)
    (ontable y4)
    (ontable y5)
    (ontable y6)
    (ontable y7)
    (ontable y8)
    (ontable y9)
    (position-free pos_back_center_bottom)
    (position-free pos_back_left_bottom)
    (position-free pos_front_center_bottom)
    (position-free pos_front_right_bottom)
    (position-free pos_middle_center_bottom)
    (position-free pos_middle_left_bottom)
    (position-free pos_middle_right_bottom)
    (position-free pos_r1_c2_bottom)
    (position-free pos_r1_c2_top)
    (position-free pos_r1_c3_bottom)
    (position-free pos_r1_c3_top)
    (position-free pos_r2_c1_bottom)
    (position-free pos_r2_c1_top)
    (position-free pos_r2_c4_bottom)
    (position-free pos_r2_c4_top)
    (position-free pos_r3_c2_bottom)
    (position-free pos_r3_c2_top)
    (position-free pos_r3_c3_bottom)
    (position-free pos_r3_c3_top)
  )
  (:goal
    (and
      (at-position g1 pos_front_center_bottom)
      (at-position g2 pos_front_right_bottom)
      (at-position g3 pos_middle_left_bottom)
      (at-position g4 pos_middle_right_bottom)
      (at-position g5 pos_back_left_bottom)
      (at-position g6 pos_back_center_bottom)
      (at-position y1 pos_r1_c2_bottom)
      (at-position y10 pos_r3_c3_bottom)
      (at-position y11 pos_r3_c2_top)
      (at-position y12 pos_r3_c3_top)
      (at-position y2 pos_r1_c3_bottom)
      (at-position y3 pos_r1_c2_top)
      (at-position y4 pos_r1_c3_top)
      (at-position y5 pos_r2_c1_bottom)
      (at-position y6 pos_r2_c4_bottom)
      (at-position y7 pos_r2_c1_top)
      (at-position y8 pos_r2_c4_top)
      (at-position y9 pos_r3_c2_bottom)
      (clear g1)
      (clear g2)
      (clear g3)
      (clear g4)
      (clear g5)
      (clear g6)
      (clear y11)
      (clear y12)
      (clear y3)
      (clear y4)
      (clear y7)
      (clear y8)
      (handempty)
      (on y11 y9)
      (on y12 y10)
      (on y3 y1)
      (on y4 y2)
      (on y7 y5)
      (on y8 y6)
      (ontable g1)
      (ontable g2)
      (ontable g3)
      (ontable g4)
      (ontable g5)
      (ontable g6)
      (ontable y1)
      (ontable y10)
      (ontable y2)
      (ontable y5)
      (ontable y6)
      (ontable y9)
    )
  )
)
